-- Inserir usuário administrador direto na tabela auth.users para teste
INSERT INTO auth.users (
  id,
  instance_id,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_token,
  confirmation_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000001',
  '00000000-0000-0000-0000-000000000000',
  'admin@nobilis-ia.com',
  '$2a$10$X4bkQ8H1Q0qSEQI2k5uN7e.zCrjf8H1fN5qbO7cGZVf3s8dK2nP6u', -- senha: admin123
  NOW(),
  NULL,
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  NULL,
  NOW(),
  '{"provider": "email", "providers": ["email"]}',
  '{"role": "admin", "nome_completo": "Administrador do Sistema"}',
  false,
  NOW(),
  NOW(),
  NULL,
  NULL,
  '',
  '',
  NULL,
  '',
  0,
  NULL,
  '',
  NULL,
  false,
  NULL
) ON CONFLICT (email) DO NOTHING;

-- Garantir que o usuário admin está na tabela users com role correto
INSERT INTO public.users (
  auth_id,
  username,
  email,
  role,
  nome_completo,
  ativo
) VALUES (
  '00000000-0000-0000-0000-000000000001',
  'admin',
  'admin@nobilis-ia.com',
  'admin',
  'Administrador do Sistema',
  true
) ON CONFLICT (email) DO UPDATE SET
  role = 'admin',
  ativo = true;